version: '3'
services:
  backend:
    build:
      context: .
      args:
        MANIFEST_VERSION: "docker-compose-build"
    ports:
      - "3131:3131"
    env_file:
      - .env

  frontend:
    image: 874822220446.dkr.ecr.us-east-1.amazonaws.com/kinsend-fe:1.0.0
    ports:
      - "8080:8080"
    env_file:
      - .env
