/* eslint-disable @typescript-eslint/naming-convention */
export enum STATUS {
  'ACTIVE' = 'ACTIVE',
  'INACTIVE' = 'INACTIVE',
  'DELETED' = 'DELETED',
  'VERIFIED' = 'VERIFIED',
  'ATTACHED' = 'ATTACHED',
  'DEFAULT' = 'DEFAULT',
}

export enum SIGNIN_PROVIDER {
  PASSWORD = 'PASSWORD',
  FACEBOOK = 'FACEBOOK',
  GOOGLE = 'GOOGLE',
}

export enum CUSTOM_FIELDS_TYPE {
  CHECKBOXES = 'CHECKBOXES',
  SINGLE_LINE_TEXT = 'SINGLE_LINE_TEXT',
  PARAGRAPH_TEXT = 'PARAGRAPH_TEXT',
  RADIO = 'RADIO',
  SELECT = 'SELECT',
}
export enum TYPE_MESSAGE {
  MESSAGE_DOMESTIC = 'MESSAGE_DOMESTIC',
  MESSAGE_INTERNATIONAL = 'MESSAGE_INTERNATIONAL',
  MESSAGE_UPDATE_DOMESTIC = 'MESSAGE_UPDATE_DOMESTIC',
  MESSAGE_UPDATE_INTERNATIONAL = 'MESSAGE_UPDATE_INTERNATIONAL',
}
export enum TYPE_PAYMENT {
  MESSAGE = 'MESSAGE',
  MESSAGE_UPDATE = 'MESSAGE_UPDATE',
}

export const REGION_DOMESTIC = 'US';

export const TTL = 60;

export const BILLING_CYCLE_ANCHOR = 30;

export const PRICE_PER_MESSAGE_DOMESTIC = 0.01;

export const PRICE_PER_MESSAGE_INTERNATIONAL = 0.16;

export const PRICE_PER_SUBS = 0.1;

export const PRICE_BASE_PLAN = 19.99;
