name: command-dispatcher

on:
  issue_comment:
    types: [created]

permissions:
  actions: write
  contents: write  # For executing the repository_dispatch event
  issues: write  # For doing the emoji reaction on an issue comment
  pull-requests: write  # For doing the emoji reaction on a PR comment
  repository-projects: read
  checks: read
  statuses: read

jobs:
  dispatcher:
    runs-on: ks-linux
    if: ${{ github.event.issue.pull_request }}
    steps:
      - name: Dispatching command
        uses: peter-evans/slash-command-dispatch@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config: >
            [
              {
                "command": "docker:push",
                "permission": "write",
                "issue_type": "pull-request"
              },
              {
                "command": "help",
                "permission": "write",
                "issue_type": "pull-request"
              }
            ]
